import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { FileDown, Table, CalendarDays, Banknote } from "lucide-react"

export default function ReportsPage() {
  const reports = [
    {
      title: "Payroll Export",
      desc: "Hours worked, travel time, and mileage per staff member.",
      icon: Banknote,
      action: "Download CSV"
    },
    {
      title: "CQC Compliance Audit",
      desc: "Missed visits, late arrivals, and care plan updates log.",
      icon: Table,
      action: "Download PDF"
    },
    {
      title: "Electronic Call Monitoring (ECM)",
      desc: "Raw check-in/check-out timestamps for council billing.",
      icon: CalendarDays,
      action: "Generate Report"
    }
  ]

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-3xl font-bold tracking-tight">Reports</h2>
          <p className="text-muted-foreground">Export data for payroll, billing, and auditing.</p>
        </div>
      </div>

      <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
        {reports.map((report, i) => (
          <Card key={i} className="hover:bg-slate-50 transition-colors cursor-pointer">
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-md font-medium">{report.title}</CardTitle>
              <report.icon className="h-5 w-5 text-muted-foreground" />
            </CardHeader>
            <CardContent>
              <p className="text-sm text-muted-foreground mt-2 mb-4 h-10">
                {report.desc}
              </p>
              <Button className="w-full" variant="outline">
                <FileDown className="mr-2 h-4 w-4" /> {report.action}
              </Button>
            </CardContent>
          </Card>
        ))}
      </div>

      <Card>
        <CardHeader>
            <CardTitle>Recent Generated Reports</CardTitle>
        </CardHeader>
        <CardContent>
            <div className="space-y-4">
                {[1,2,3].map((_, i) => (
                    <div key={i} className="flex items-center justify-between border-b pb-4 last:border-0 last:pb-0">
                        <div className="flex items-center gap-4">
                            <div className="h-10 w-10 bg-blue-100 text-blue-600 rounded flex items-center justify-center">
                                <FileDown className="h-5 w-5" />
                            </div>
                            <div>
                                <p className="font-medium">Payroll_Nov_2025.csv</p>
                                <p className="text-xs text-muted-foreground">Generated by Admin on 01/12/2025</p>
                            </div>
                        </div>
                        <Button size="sm" variant="ghost">Download Again</Button>
                    </div>
                ))}
            </div>
        </CardContent>
      </Card>
    </div>
  )
}